package com.example.servingwebcontent;

import com.example.servingwebcontent.Database.userAiven;
import com.example.servingwebcontent.Model.User;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

@SpringBootApplication
public class ServingWebContentApplication {

    private static final Logger log = LoggerFactory.getLogger(ServingWebContentApplication.class);

    public static void main(String[] args) {
        SpringApplication.run(ServingWebContentApplication.class, args);
    }

    // Seed a default test user at startup (id auto-generated by DB). Safe to run repeatedly.
    @Bean
    CommandLineRunner seedDefaultUser(userAiven ua) {
        return args -> {
            try {
                String email = "testuser@gmail.com";
                String password = "123456";
                User existed = ua.getByEmail(email);
                if (existed == null) {
                    User u = new User();
                    u.setName("Test User");
                    u.setGender(User.Gender.Male);
                    u.setBirthDate("2000-01-01");
                    u.setPhoneNumber("0900000000");
                    u.setEmail(email);
                    u.setAddress("HN");
                    u.setPassword(password);
                    u.setUserType(User.UserType.Customer);
                    boolean created = ua.register(u);
                    if (created) {
                        log.info("Seeded test account: {} / {}", email, password);
                    } else {
                        log.info("Test account already present (email in use): {}", email);
                    }
                } else {
                    // ensure password matches our expected test password
                    if (!password.equals(existed.getPassword())) {
                        ua.updatePasswordByEmail(email, password);
                        log.info("Updated test account password for {}", email);
                    } else {
                        log.info("Test account already exists and password matches.");
                    }
                }
            } catch (Exception e) {
                log.warn("Could not seed test user: {}", e.getMessage());
            }
        };
    }

}
